const XML_ILLEGAL = /[-\u0008\u000B\u000C\u000E-\u001F\uFFFE\uFFFF]/;

export function escapeXml(value) {
  const text = String(value ?? '');
  if (XML_ILLEGAL.test(text)) throw new Error('Input contains characters that are illegal in XML 1.0.');
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}
function tag(name, value, indent = 0) { if (value === undefined || value === null || value === '') return ''; return `${' '.repeat(indent)}<${name}>${escapeXml(value)}</${name}>`; }
function component(name, arch, body, indent = 4) { const attrs = `name="${name}" processorArchitecture="${arch}" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS"`; return [`${' '.repeat(indent)}<component ${attrs}>`, body, `${' '.repeat(indent)}</component>`].filter(Boolean).join('\n'); }
function bool(value) { return value ? 'true' : 'false'; }
function utf16leBase64(text) { const bytes = []; for (const ch of String(text)) { const c = ch.charCodeAt(0); bytes.push(c & 255, c >> 8); } let binary = ''; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.slice(i, i + 0x8000)); return btoa(binary); }
function encodedPassword(password) { return utf16leBase64(`${password}Password`); }
function archOf(config) { return config.architecture === 'arm64' ? 'arm64' : 'amd64'; }
function localeOf(config) { return config.installLanguage === 'en' ? 'en-US' : 'hu-HU'; }
function computerName(config) { const raw = String(config.computerName || 'PC').trim().toUpperCase().replace(/[^A-Z0-9-]/g, ''); return config.randomSuffix ? '*' : (raw || '*').slice(0, 15); }

function windowsPe(config, arch, locale) {
  const lines = ['  <settings pass="windowsPE">'];
  lines.push(component('Microsoft-Windows-International-Core-WinPE', arch, ['      <SetupUILanguage>', tag('UILanguage', locale, 8), '      </SetupUILanguage>', tag('InputLocale', config.addEnglishKeyboard && locale === 'hu-HU' ? '040e:0000040e;0409:00000409' : locale === 'hu-HU' ? '040e:0000040e' : '0409:00000409', 6), tag('SystemLocale', locale, 6), tag('UILanguage', locale, 6), tag('UserLocale', locale, 6)].join('\n')));
  const setup = ['      <UserData>', '        <AcceptEula>true</AcceptEula>', '      </UserData>'];
  if (config.productKey?.trim()) setup.push('      <ProductKey>', tag('Key', config.productKey.trim(), 8), '      </ProductKey>');
  if (config.partitioning?.enabled && ['auto', 'autocd'].includes(config.partitioning.mode)) setup.push('      <DiskConfiguration>', '        <WillShowUI>OnError</WillShowUI>', '        <Disk wcm:action="add">', '          <DiskID>0</DiskID>', '          <WillWipeDisk>true</WillWipeDisk>', '          <CreatePartitions>', '            <CreatePartition wcm:action="add"><Order>1</Order><Size>500</Size><Type>EFI</Type></CreatePartition>', '            <CreatePartition wcm:action="add"><Order>2</Order><Size>16</Size><Type>MSR</Type></CreatePartition>', '            <CreatePartition wcm:action="add"><Order>3</Order><Extend>true</Extend><Type>Primary</Type></CreatePartition>', '          </CreatePartitions>', '          <ModifyPartitions>', '            <ModifyPartition wcm:action="add"><Order>1</Order><PartitionID>1</PartitionID><Format>FAT32</Format><Label>System</Label></ModifyPartition>', '            <ModifyPartition wcm:action="add"><Order>2</Order><PartitionID>2</PartitionID></ModifyPartition>', '            <ModifyPartition wcm:action="add"><Order>3</Order><PartitionID>3</PartitionID><Format>NTFS</Format><Label>Windows</Label><Letter>C</Letter></ModifyPartition>', '          </ModifyPartitions>', '        </Disk>', '      </DiskConfiguration>', '      <ImageInstall><OSImage><InstallTo><DiskID>0</DiskID><PartitionID>3</PartitionID></InstallTo></OSImage></ImageInstall>');
  lines.push(component('Microsoft-Windows-Setup', arch, setup.join('\n')), '  </settings>'); return lines.join('\n');
}
function specialize(config, arch) { return ['  <settings pass="specialize">', component('Microsoft-Windows-Shell-Setup', arch, tag('ComputerName', computerName(config), 6)), '  </settings>'].join('\n'); }
function oobe(config, arch, locale) {
  const shell = ['      <OOBE>', '        <HideEULAPage>true</HideEULAPage>', '        <HideWirelessSetupInOOBE>false</HideWirelessSetupInOOBE>', '        <ProtectYourPC>1</ProtectYourPC>', '      </OOBE>', tag('TimeZone', config.timeZone || (locale === 'hu-HU' ? 'Central Europe Standard Time' : 'UTC'), 6)];
  const username = String(config.username || '').trim();
  if (username) shell.push('      <UserAccounts>', '        <LocalAccounts>', '          <LocalAccount wcm:action="add">', tag('Name', username, 12), '            <Group>Users</Group>', '            <Password>', tag('Value', encodedPassword(config.password || ''), 14), '              <PlainText>false</PlainText>', '            </Password>', '          </LocalAccount>', '        </LocalAccounts>', '      </UserAccounts>');
  if (config.autoLogin && username) shell.push('      <AutoLogon>', '        <Enabled>true</Enabled>', tag('Username', username, 8), '        <Password>', tag('Value', encodedPassword(config.password || ''), 10), '          <PlainText>false</PlainText>', '        </Password>', '        <LogonCount>1</LogonCount>', '      </AutoLogon>');
  return ['  <settings pass="oobeSystem">', component('Microsoft-Windows-International-Core', arch, [tag('InputLocale', locale === 'hu-HU' && config.addEnglishKeyboard ? '040e:0000040e;0409:00000409' : locale === 'hu-HU' ? '040e:0000040e' : '0409:00000409', 6), tag('SystemLocale', locale, 6), tag('UILanguage', locale, 6), tag('UserLocale', locale, 6)].join('\n')), component('Microsoft-Windows-Shell-Setup', arch, shell.join('\n')), '  </settings>'].join('\n');
}
export function generateXml(config = {}) { const arch = archOf(config); const locale = localeOf(config); return ['<?xml version="1.0" encoding="utf-8"?>', '<!-- Generated for Windows 11 25H2. Password values are obfuscated, not encrypted. Delete the answer file after use. -->', '<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">', windowsPe(config, arch, locale), specialize(config, arch), oobe(config, arch, locale), '</unattend>'].join('\n'); }
export function validateGeneratedXml(xml) { if (!xml || !xml.includes('<unattend ') || !xml.endsWith('</unattend>')) throw new Error('Generated answer file is incomplete.'); if (/<PlainText>true<\/PlainText>/.test(xml)) throw new Error('Plaintext credentials are forbidden.'); if (/LabConfig|ExecutionPolicy Bypass|certutil|BypassNRO|ConsentPromptBehaviorAdmin/.test(xml)) throw new Error('Unsupported or unsafe deployment content detected.'); if (!/<TimeZone>/.test(xml)) throw new Error('TimeZone is required for unattended deployment.'); if (typeof DOMParser !== 'undefined') { const parsed = new DOMParser().parseFromString(xml, 'application/xml'); if (parsed.querySelector('parsererror')) throw new Error('Generated answer file is not well-formed XML.'); } return xml; }
